module.exports={
    preset:'ts-jest',
    setupFiles:['dotenv/config'],
    testEnvironment:'node',
    transform:{
        'node_modules/variables/.+\\.(j|t)sx?$':'ts-jest',
    },
    transformIgnorePatterns:['node_modules/(?!variables/.*)'],
    moduleDirectories:['node_modules','src'],
}
